# Generated by Django 3.2.6 on 2021-08-28 19:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pages-images')),
                ('about', ckeditor.fields.RichTextField()),
                ('services', ckeditor.fields.RichTextField()),
                ('team', ckeditor.fields.RichTextField()),
                ('policy', ckeditor.fields.RichTextField()),
                ('terms', ckeditor.fields.RichTextField()),
                ('web_desing', ckeditor.fields.RichTextField()),
                ('web_development', ckeditor.fields.RichTextField()),
                ('graphic_design', ckeditor.fields.RichTextField()),
                ('marketing', ckeditor.fields.RichTextField()),
                ('product_management', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Main_page',
                'verbose_name_plural': 'Main_pages',
                'db_table': 'Main_pages',
            },
        ),
    ]
