# Generated by Django 3.2.6 on 2021-08-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='title',
        ),
    ]
