# Generated by Django 3.2.6 on 2021-08-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0002_auto_20210828_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pages-images')),
            ],
            options={
                'verbose_name': 'Page_detail',
                'verbose_name_plural': 'Page_details',
                'db_table': 'Page_detail',
            },
        ),
    ]
