# Generated by Django 3.2.6 on 2021-08-28 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0003_pagedetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageDetail',
        ),
        migrations.RenameField(
            model_name='pages',
            old_name='about',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='graphic_design',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='marketing',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='product_management',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='services',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='team',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='web_desing',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='web_development',
        ),
        migrations.AddField(
            model_name='pages',
            name='detail',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pages',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='page-images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pages',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
