# Generated by Django 3.2.6 on 2021-08-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0002_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_action_title', models.CharField(max_length=50)),
                ('call_action_text', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name': 'call_action',
                'verbose_name_plural': 'call_actions',
                'db_table': 'call_action',
            },
        ),
    ]
