# Generated by Django 3.2.6 on 2021-08-23 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='detail',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
