# Generated by Django 3.2.6 on 2021-08-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0005_about_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=45)),
                ('text', models.CharField(max_length=65)),
                ('link', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='hero-images')),
            ],
            options={
                'verbose_name': 'header',
                'verbose_name_plural': 'headers',
                'db_table': 'header',
            },
        ),
    ]
