# Generated by Django 3.2.6 on 2021-08-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0006_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=55)),
                ('content', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/why-us')),
            ],
            options={
                'verbose_name': 'why_us',
                'db_table': 'why_us',
            },
        ),
        migrations.CreateModel(
            name='WhyUsAsks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('detail', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'why_ask',
                'verbose_name_plural': 'why_asks',
                'db_table': 'why_ask',
            },
        ),
    ]
