# Generated by Django 3.2.6 on 2021-08-28 10:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0008_auto_20210828_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdetail',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
